version: "3"

services:
  sboot:
    image: sb-product-service
    ports:
      - "9090:9090"
    networks:
      - cinet
    environment:
      - DB_HOST=db
    depends_on:
      - db

  go:
    image: go-post-service
    ports:
      - "3000:3000"
    networks:
      - cinet
    environment:
      - DB_HOST=db
      - GIN_MODE=release
    depends_on:
      - db

  quarkus:
    image: quarkus-post-service
    ports:
      - "8080:8080"
    networks:
      - cinet
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"    
    networks:
      - cinet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  cinet:
    driver: bridge