
spring:
  application:
    name: product-service
  jpa:
    show-sql: false  datasource:    hikari:      maximum-pool-size: 50

server:
  port: 9090    
 
spring.datasource.platform: postgres
spring.datasource.url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
spring.datasource.username:  postgres
spring.datasource.password:  postgres 

spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


  