apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cna
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cna
  labels:
    app: postgres
spec:
  ports:
   - targetPort: 5432 
     port: 5432
  selector:
   app: postgres


---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: cna
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: cna
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
        tier: backend
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo


