apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: cna
  labels:
    app: postgres
data:
  QUARKUS_MONGODB_CONNECTION_STRING : mongodb://mongo:27017
  COM_ETERATION_DEMO_USER_POSTSERVICECLIENT_MP_REST_URL : http://post-service:8080

---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: cna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
      version: v1
  template:
    metadata:
      labels:
        app: user-service
        version: v1
    spec:
      containers:
      - name: user-service
        image: quarkus-user-service:latest
        imagePullPolicy: IfNotPresent
        envFrom:
            - configMapRef:
                name: user-service-config      
        ports:
        - containerPort: 8090
          protocol: TCP
        resources:
           limits:
             cpu: "50m"
             memory: "256Mi"
---

kind: Service
apiVersion: v1
metadata:
  name: user-service
  namespace: cna
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
  - protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 32090
