apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: cna
  labels:
    app: elasticsearch
data:
  discovery.type: single-node




---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: cna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:7.6.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9200
          envFrom:
            - configMapRef:
                name: elasticsearch-config


---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: cna
  labels:
    app: elasticsearch
spec:
  ports:
   - targetPort: 9200 
     port: 9200
  selector:
   app: elasticsearch
