apiVersion: v1
kind: ConfigMap
metadata:
  name: post-query-service-config
  namespace: cna
  labels:
    app: postgres
data:
  ELASTICSEARCH_HOST: elasticsearch
  ELASTICSEARCH_PORT: "9200"
  MP_MESSAGING_INCOMING_POST_READ_HOST: amq


---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-query-service
  namespace: cna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-query-service
      version: v1
  template:
    metadata:
      labels:
        app: post-query-service
        version: v1
    spec:
      initContainers:
      - name: check-amq-ready
        image: busybox
        command: ['sh', '-c', 
          'while ! `nc -z amq 5672`; do sleep 3; done']    
      containers:
      - name: post-query-service
        image: quarkus-post-query-service:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/live"
            port: 8070
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/ready"
            port: 8070
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10  
        envFrom:
            - configMapRef:
                name: post-query-service-config      
        ports:
        - containerPort: 8070
          protocol: TCP
        resources:
           limits:
             cpu: "50m"
             memory: "256Mi"
---

kind: Service
apiVersion: v1
metadata:
  name: post-query-service
  namespace: cna
spec:
  type: NodePort
  selector:
    app: post-query-service
  ports:
  - protocol: TCP
    port: 8070
    targetPort: 8070
    nodePort: 32070
